In [105]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [106]:
# import data
train=pd.read_csv('mnist_train.csv')
test=pd.read_csv('mnist_test.csv')

In [107]:
# explore data
train.info()
train.head(5)
train.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59999 entries, 0 to 59998
Columns: 785 entries, 5 to 0.617
dtypes: int64(785)
memory usage: 359.3 MB


5        0      0.1      0.2      0.3      0.4      0.5  \
count  59999.000000  59999.0  59999.0  59999.0  59999.0  59999.0  59999.0   
mean       4.453924      0.0      0.0      0.0      0.0      0.0      0.0   
std        2.889294      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%        2.000000      0.0      0.0      0.0      0.0      0.0      0.0   
50%        4.000000      0.0      0.0      0.0      0.0      0.0      0.0   
75%        7.000000      0.0      0.0      0.0      0.0      0.0      0.0   
max        9.000000      0.0      0.0      0.0      0.0      0.0      0.0   

           0.6      0.7      0.8   ...            0.608         0.609  \
count  59999.0  59999.0  59999.0   ...     59999.000000  59999.000000   
mean       0.0      0.0      0.0   ...         0.200437      0.088868   
std        0.0      0.0      0.0   ...         6.042522      3.956222   
min        0.0      0.0      0.0   ...         0.000000      0.000000   
25%        0.0      0.0      0.0   ...         0.000000      0.000000   
50%        0.0      0.0      0.0   ...         0.000000      0.000000   
75%        0.0      0.0      0.0   ...         0.000000      0.000000   
max        0.0      0.0      0.0   ...       254.000000    254.000000   

              0.610         0.611         0.612         0.613    0.614  \
count  59999.000000  59999.000000  59999.000000  59999.000000  59999.0   
mean       0.045634      0.019284      0.015117      0.002000      0.0   
std        2.839868      1.686784      1.678297      0.346603      0.0   
min        0.000000      0.000000      0.000000      0.000000      0.0   
25%        0.000000      0.000000      0.000000      0.000000      0.0   
50%        0.000000      0.000000      0.000000      0.000000      0.0   
75%        0.000000      0.000000      0.000000      0.000000      0.0   
max      253.000000    253.000000    254.000000     62.000000      0.0   

         0.615    0.616    0.617  
count  59999.0  59999.0  59999.0  
mean       0.0      0.0      0.0  
std        0.0      0.0      0.0  
min        0.0      0.0      0.0  
25%        0.0      0.0      0.0  
50%        0.0      0.0      0.0  
75%        0.0      0.0      0.0  
max        0.0      0.0      0.0  

[8 rows x 785 columns]

In [108]:
test.info()
test.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Columns: 785 entries, 7 to 0.667
dtypes: int64(785)
memory usage: 59.9 MB


7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...    0.658  0.659  0.660  \
0  2  0    0    0    0    0    0    0    0    0  ...        0      0      0   
1  1  0    0    0    0    0    0    0    0    0  ...        0      0      0   
2  0  0    0    0    0    0    0    0    0    0  ...        0      0      0   
3  4  0    0    0    0    0    0    0    0    0  ...        0      0      0   
4  1  0    0    0    0    0    0    0    0    0  ...        0      0      0   

   0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [109]:
# get important parameters
#k -calss
#n_obs of observations
#n_var
k=train.iloc[:,0].max()
n_obst = len(train)
n_var=train.shape[1]-1
# prepare for train
x_train=train.iloc[:,1:]
y_train=train.iloc[:,0]
x_test=test.iloc[:,1:]
y_test=test.iloc[:,0]


In [110]:
# get probability matrix
def softmax(z):
# Normalize the scores beforehand with max as zero to avoid 
# numerical problems with the exponential
    exps=np.exp(z-np.max(z,axis=0,keepdims=True))
    s=exps/np.sum(exps,axis=0,keepdims=True)
    return s

In [111]:
'''
get the derivative of softmax function
s is k*n matrix
x is n*d  matrix 
output k*d matrix 
k-class, d-# varaibles,n-# of cases
'''
def deriv_soft(s,x,y):
    n_obst=x.shape[0]
    # select the goal label and substrcat 1
    s[y-1,np.arange(n_obst)] -= 1
    return np.dot(s,x)
    

In [112]:

   
def get_mini_batch(x_train,y_train,size=2**10):
    
    n_samples=x_train.shape[0]
    x_mini_batches=list()
    y_mini_batches=list()
    index=np.random.permutation(n_samples)
    x_shuffle=x_train.iloc[index,:]
    y_shuffle=y_train.iloc[index,]
    itr=round(n_samples/size)
    print(itr)

    for i in range(itr):
       
        x_mini=x_shuffle.iloc[i*size:(i+1)*size,:]
        y_mini=y_shuffle.iloc[i*size:(i+1)*size,]
        x_mini_batches.append(x_mini)
        y_mini_batches.append(y_mini)
        
    return x_mini_batches,y_mini_batches,itr

In [113]:
def get_gd(x_train,y_train,w):
    b=x_train.shape[0]
    z=np.dot(x_train,w).T
    s=softmax(z)
    gd=deriv_soft(s,x_train,y_train)/b   
    return gd

In [114]:
'''
itr=number of iteration for gradient dexcent
a is learning rate
size is size of mini bacth
itr_mini :number of mini batch to get average gd
'''
def multi_logistic_train(x_train, y_train, itre=100,a=0.05):
    x_minis,y_minis,itr=get_mini_batch(x_train,y_train)
    n_var=x_train.shape[1]
    # intintial w
    w=np.random.rand(k*n_var)
    w=w.reshape([n_var,k])
    for j in range(itre):
        for i in range(itr):
            x_mini=x_minis[i]
            y_mini=y_minis[i]
            # gradient descent
            gd=get_gd(x_mini,y_mini,w)
            w=w-a*gd.T     
    return(w)

In [115]:
# train data
w=multi_logistic_train(x_train, y_train)
print(w.shape)
print(w)

59
(784, 9)
[[0.89085808 0.82227224 0.20468146 ... 0.81949629 0.83508507 0.77619228]
 [0.16700744 0.74534111 0.06693602 ... 0.09415332 0.71761686 0.01697347]
 [0.07546678 0.37077816 0.06514859 ... 0.4901719  0.26743604 0.5986437 ]
 ...
 [0.70909838 0.02988195 0.70821881 ... 0.43576798 0.74689689 0.67708557]
 [0.7336167  0.8635206  0.21714516 ... 0.37635078 0.67171121 0.91653657]
 [0.76989937 0.86618061 0.74036647 ... 0.86155934 0.24348061 0.74268463]]


In [116]:
# predict
def multi_logistic_predict(x_test,w):
    z=np.dot(x_test,w)
    y_pred=np.argmax(z,axis=1)
    return y_pred

In [117]:
def accuracy(y_test,y_pred):
    n_test=y_test.shape[0]
    correct=np.sum(y_test==y_pred)
    return correct/n_test



In [120]:
#predict test dataset
y_pred=multi_logistic_predict(x_test,w)
print(y_pred)

[1 0 8 ... 3 4 5]


In [121]:
# report accuracy
accu=accuracy(y_test,y_pred)
print(accu)

0.018001800180018002


In [85]:
np.save('w_multi',w)

In [103]:
cm=np.zeros((10,10))*1.
n=y_pred.shape[0]
for t in range(n):
    i=y_pred[t]
    j=y_test[t]
    cm[i,j]+=1.

        

In [124]:
pd.crosstab(y_test,y_pred,rownames='T',colnames='P')

P     0    1    2    3    4    5    6  7    8
T                                            
0     0    2    2    2   13   12    1  0  948
1  1117    3    2    0    8    3    1  0    1
2    15  928   28   18    8    9    9  0   17
3     1   20  884    4   82    2    9  0    8
4     5    2    4  934    0   10    2  0   25
5     4    3   20   18  798   12    6  0   31
6     3    7    1   22   33  871    2  0   19
7     7   32   12   10    1    0  888  0   77
8    41   93  157   62  436   42   11  1  131
9     7    0   19   64   29    0   21  0  869