In [12]:
import numpy as np
import pandas as pd
import matplotlib as plt
!conda install --yes cvxopt

WARNING conda.base.context:use_only_tar_bz2(632): Conda is constrained to only using the old .tar.bz2 file format because you have conda-build installed, and it is <3.18.3.  Update or remove conda-build to get smaller downloads and faster extractions.
Solving environment: done

## Package Plan ##

  environment location: /anaconda3

  added / updated specs:
    - cvxopt


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.7.12               |           py37_0         3.0 MB
    cvxopt-1.2.0               |   py37hcab12e0_0         488 KB
    glpk-4.65                  |       ha8bbb54_2         1.1 MB
    metis-5.1.0                |       h0a44026_4         4.1 MB
    suitesparse-5.2.0          |       h7413580_0         2.5 MB
    tbb-2019.4                 |       h04f5b5a_0         163 KB
    ------------------------------------------------------------
                          

In [169]:
data=pd.read_csv('/Users/yangxiaomin/Documents/courses/csci 5525/5525HW_2/hw2data.csv')
data.head()




1.764052345967664  0.4001572083672233  -1.0
0           0.978738            2.240893  -1.0
1           1.867558           -0.977278   1.0
2           0.950088           -0.151357   1.0
3          -0.103219            0.410599   1.0
4           0.144044            1.454274  -1.0

In [377]:
# split data into train test
n_t=data.shape[0]
n_train=round(0.8*n_t)
n_test=n_t-n_train
x_train=data.iloc[:n_train,:2]
x_test=data.iloc[n_train:,:2]
y_train=data.iloc[:n_train,[2]]
y_test=data.iloc[n_train:,[2]]



In [287]:
# computing H matrx
# x_train it's n*2 matrix, y_train it's n*1 matrix
# x*y 
#H it's a n*n matrix
#A = matrix(A, (1, m), 'd')

import cvxopt
#initialize c
c=5

# calculate H atrix
H=np.dot(y_train*x_train,(y_train*x_train).T)*1.

q=-np.ones((n_train,1))
G=np.vstack((-np.eye(n_train),np.eye(n_train)))
p=H
h=np.hstack((np.zeros(n_train),np.ones(n_train)*c))
b=np.zeros(1)
q=cvxopt.matrix(q)
G=cvxopt.matrix(G)
p=cvxopt.matrix(p)
h=cvxopt.matrix(h)
A=cvxopt.matrix(y_train.T)
b=cvxopt.matrix(b)


        


In [288]:
# solve problem
sol = cvxopt.solvers.qp(p, q, G, h, A, b)
# langurange multipliers
a=np.ravel(sol['x'])

print(a)

     pcost       dcost       gap    pres   dres
 0: -4.7884e+03 -1.9716e+04  1e+04  6e-14  2e-13
 1: -6.2776e+03 -8.0898e+03  2e+03  1e-14  1e-13
 2: -7.4387e+03 -7.9457e+03  5e+02  3e-14  1e-13
 3: -7.4790e+03 -7.9704e+03  5e+02  2e-13  1e-13
 4: -7.5403e+03 -7.9811e+03  4e+02  3e-14  1e-13
 5: -7.6175e+03 -7.9755e+03  4e+02  2e-13  1e-13
 6: -7.6854e+03 -7.9573e+03  3e+02  3e-13  1e-13
 7: -7.7474e+03 -7.9327e+03  2e+02  6e-14  1e-13
 8: -7.7840e+03 -7.9150e+03  1e+02  9e-14  1e-13
 9: -7.8296e+03 -7.8903e+03  6e+01  3e-13  1e-13
10: -7.8578e+03 -7.8698e+03  1e+01  2e-16  2e-13
11: -7.8598e+03 -7.8604e+03  6e-01  2e-13  2e-13
12: -7.8600e+03 -7.8600e+03  6e-03  2e-13  2e-13
Optimal solution found.
[4.99473873 4.99999828 4.99999821 ... 4.9999986  4.98686579 4.99999889]


In [292]:
# pick support point
ind=a>0
a=a[ind]
x_train=x_train[ind]
y_train=y_train[ind]
a.shape
y_train.shape


(1599, 1)

In [305]:
# compute w
n_t=a.shape[0]
a=a.reshape((n_t,1))
w=np.multiply(y_train,a)*x_train
w=np.sum(w,axis=0)
print(w.shape)


(2,)


In [ ]:
# predict
def predict(x,c):
    w=train
    

In [328]:
z=np.dot(x_train,w.T)
pred=np.sign(z)
pred=pred.reshape(n_t,1)
print(pred)
print(pred.shape)

acc=pred==y_train
acc.shape
sum(acc)


[[ 1.]
 [ 1.]
 [ 1.]
 ...
 [-1.]
 [-1.]
 [-1.]]
(1599, 1)


array([818])

In [343]:
z=np.dot(x_test,w.T)
pred=np.sign(z)
pred=pred.reshape(n_test,1)

print(pred.shape)

acc=pred==y_test
acc.shape
np.sum(acc)

(400, 1)


-1.0    192
dtype: int64

In [344]:
def svmfit(x_train,y_train,c):
    y_train=pd.DataFrame.as_matrix(y_train)
    n_train=x_train.shape[0]
    #compute H matrix
    H=np.dot(y_train*x_train,(y_train*x_train).T)*1.
    # construct cvsmatrix
    q=-np.ones((n_train,1))
    G=np.vstack((-np.eye(n_train),np.eye(n_train)))
    p=H
    h=np.hstack((np.zeros(n_train),np.ones(n_train)*c))
    b=np.zeros(1)
    q=cvxopt.matrix(q)
    G=cvxopt.matrix(G)
    p=cvxopt.matrix(p)
    h=cvxopt.matrix(h)
    A=cvxopt.matrix(y_train.T)
    b=cvxopt.matrix(b)
    
    # solve problem
    sol = cvxopt.solvers.qp(p, q, G, h, A, b)
    # langurange multipliers
    a=np.ravel(sol['x'])
    # pick support point
    ind=a>0
    a=a[ind]
    x_train=x_train[ind]
    y_train=y_train[ind]
    # compute w
    n_t=a.shape[0]
    a=a.reshape((n_t,1))
    w=np.multiply(y_train,a)*x_train
    w=np.sum(w,axis=0)
    
    return w
    

    

In [346]:
def predict(x_test,w):
    z=np.dot(x_test,w.T)
    pred=np.sign(z)
    pred=pred.reshape(n_test,1)
    return pred

    
    
    

In [352]:
def accuary(y_test,y_pred):
    n_test=y_test.shape[0]
    correct=np.sum(y_test==y_pred.reshape(n_test,1))
    return correct/n_test

In [357]:

def cross_validation(x_train,y_train):
    
    n=x_train.shape[0]
    index = np.random.permutation(n)
    x_shuffled=x_train.iloc[index,:]
    y_shuffled=y_train.iloc[index,:]
    return x_shuffled,y_shuffled
    

   

In [379]:
cross_validation(x_train,y_train)

(      1.764052345967664  0.4001572083672233
 1145           0.342427           -0.223426
 1174           0.311124           -1.078361
 411           -0.667720            0.326963
 588           -0.625557            0.992137
 1535          -1.824080           -0.578709
 1114           1.103504           -0.575256
 305            0.605120            0.895556
 1212          -0.550799            0.792041
 1232          -0.590757            0.971970
 1418          -0.888645           -0.135810
 1525          -1.007555            0.566869
 1573           0.157069           -0.980459
 1231           1.222877           -2.086510
 672            0.480424           -0.968186
 1575           1.082591            0.368004
 187            0.643314           -1.570623
 444           -0.647181            0.472247
 1              1.867558           -0.977278
 1154           0.766990           -1.026007
 442            0.936399           -0.525641
 800           -1.006037           -0.821550
 19       

In [361]:
def get_next_train_valid(X_shuffled, Y_shuffled, itr):
    """
    - itr value can tell you which fold you pick up for valid and rest go to training
    - use 1 fold for validation and all other folds for training
    - in next iteration, use a different fold for validation and remaining folds for training
        
    Basically, here you will determine which fold goes for validation and which ones for training
    """
    size=len(Y_shuffled)/10
 
    validL=round(size*(itr-1))
    validR=round(size*(itr))
    print('validL:'+str(validL))
    print('validR:'+str(validR))

    X_valid=X_shuffled.iloc[validL:validR]
   
    y_valid=Y_shuffled.iloc[validL:validR]
    
    X_train=pd.concat([X_shuffled.iloc[0:validL],X_shuffled.iloc[validR:]])  
    y_train=pd.concat([Y_shuffled.iloc[0:validL],Y_shuffled.iloc[validR:]]) 
    print('X_t:'+str(X_train.shape))
    print('X_v:'+str(X_valid.shape))
    print('y_t:'+str(y_train.shape))
    print('y_v:'+str(y_valid.shape))
    return X_train,y_train,X_valid, y_valid
    #return training and validation data

In [362]:
get_next_train_valid(x_train,y_train,1)

validL:0
validR:160
X_t:(1439, 2)
X_v:(160, 2)
y_t:(1439, 1)
y_v:(160, 1)


(      1.764052345967664  0.4001572083672233
 160            0.274516           -0.890915
 161           -1.157355           -0.312292
 162           -0.157667            2.256723
 163           -0.704700            0.943261
 164            0.747188           -1.188945
 165            0.773253           -1.183881
 166           -2.659172            0.606320
 167           -1.755891            0.450934
 168           -0.684011            1.659551
 169            1.068509           -0.453386
 170           -0.687838           -1.214077
 171           -0.440923           -0.280355
 172           -0.364694            0.156704
 173            0.578521            0.349654
 174           -0.764144           -1.437791
 175            1.364532           -0.689449
 176           -0.652294           -0.521189
 177           -1.843070           -0.477974
 178           -0.479656            0.620358
 179            0.698457            0.003771
 180            0.931848            0.339965
 181      

In [378]:

      

def main(x_train,y_train,x_test,y_test,c):
    x_shuffled,y_shuffled=cross_validation(x_train,y_train)
    accu_cv=list()
    accu_t=list()
    for itr in range(1,11):
        x_train, y_train, x_valid, y_valid=get_next_train_valid(x_shuffled, y_shuffled, itr)
        #ntrain data using train set
        w=svmfit(x_train,y_train,1)
        #predict in v set
        pred=predict(x_valid,w)
        # predict in test set
        tpred=predict(x_test,w)
        # caculate accuray
        a=accuracy(pred,y_train)
        at=accuracy(tpred,y_test)
        accu_cv.append(a)
        accu_t.append(at)
    cv_a=np.mean(accu_cv)
    cv_t=np.mean(accu_t)
    
    return cv_a,cv_t
        
    

In [376]:
main(x_train,y_train,x_test,y_test,4)

validL:0
validR:160
X_t:(1439, 2)
X_v:(160, 2)
y_t:(1439, 1)
y_v:(160, 1)


TypeError: 'A' must be a 'd' matrix with 1439 columns

In [368]:
test=c()
test.append(1)

TypeError: 'int' object is not callable